INPUT_FILE_NET_1 ="../../Data/NAPAbench/5-way/CG_set/Family_10/A.net"
INPUT_FILE_NET_2 ="../../Data/NAPAbench/5-way/CG_set/Family_10/B.net"
#INPUT_FILE = "../Data/GHOSTData.fixed/Data/CJejuni/cjejuni.gexf"
GEXF_FORMAT=".gexf"
NET_FORMAT=".net"