
RESULT_LOG_FILE = "result.txt"
NAPA_PATH ="../../Data/NAPAbench"
INPUT_FILE_1_NAME = "A"
INPUT_FILE_2_NAME = "B"
#INPUT_FILE = "../Data/GHOSTData.fixed/Data/CJejuni/cjejuni.gexf"
GEXF_FORMAT=".gexf"
NET_FORMAT=".net"
KMEANS_PATH = "../../Data/Kmeans"
KMEANSH_PATH = "../../Data/KmeansH"
SPECTRAL_PATH = "../../Data/SpectralC"
GHOST_PATH = "../../GHOST"
MCL = "mcl {0} --abc -o {1} -I {2} > /dev/null 2>&1"
FINAL_SCORE_DIR = "Score_Dir"
FINAL_RESULT = "Final_result"
EC_ICS_REGEX = 'Edge correctness \d+ \/ \d+ = (\d+\.\d+)%\nICS = (\d+\.\d+)%'
RESULT_FILE = "result.af"
PROF = "PROF"
OURS = "OURS"

