DATASET_USED = "5way_CG_10"
RESULT_LOG_FILE = "result.txt"
INPUT_FILE_1 ="../../Data/NAPAbench/5-way/CG_set/Family_10/A"
INPUT_FILE_1_NAME = "A"
INPUT_FILE_2 ="../../Data/NAPAbench/5-way/CG_set/Family_10/B"
INPUT_FILE_2_NAME = "B"
#INPUT_FILE = "../Data/GHOSTData.fixed/Data/CJejuni/cjejuni.gexf"
GEXF_FORMAT=".gexf"
NET_FORMAT=".net"
KMEANS_PATH = "../../Data/Kmeans"
GHOST_PATH = "../../GHOST"
MCL = "/tmp/MCL/bin/mcl {0} --abc -o {1} -I 1.3 > /dev/null 2>&1"
FINAL_SCORE_DIR = "Score_Dir"
FINAL_RESULT = "Final_result"
EC_ICS_REGEX = 'Edge correctness \d+ \/ \d+ = (\d+\.\d+)%\nICS = (\d+\.\d+)%'
RESULT_FILE = "result.af"
PROF = "PROF"
OURS = "OURS"

